### PR TITLE
Expansion Tests

### PR DESCRIPTION
**Pull request by angelhof**

### CODE REVIEW

**Comment by angelhof** [comment]
@mgree I incorporated the tests that you had written for expansion but some of them fail. I am not sure which of those are expected to fail (due to not being implemented) and which of those are not supposed to fail. Could you take a look at this (https://github.com/binpash/sh-expand/actions/runs/5136835681/jobs/9244092408?pr=4) when you have some time (not urgent) and let me know which of those should and should not fail?

**Comment by mgree** [comment]
Ah: the analysis is bit-rotted. We gave up on it when we realized that we could do the analysis and expansion at the same time. We could of course fix the analysis, if we wanted to.

Pushed an attempt at a fix, but som other stuff needs to change. safe1.sh uses `~` expansion but has my home directory hard coded; a similar problem with `$PWD` in safe4.sh.

**Comment by mgree** [comment]
Okay, looking more closely we should be able to expand `$PWD` and `~` correctly... but the expander doesn't do it properly. For example, `expand.py` line 449 just blows up on an assignment, but we should be recursively expanding and updating the environment.

I'm guessing I wrote these tests before we realized we couldn't handle _any_ side effects in the pash expander... and then they bitrotted.

**Comment by angelhof** [comment]
Oh I see. I think it is OK if we don't fix all the tests now, as long as we have a clear understanding of what we can support and what not (so that we comment out some tests and address them in the future). Based on this discussion now it seems that the failing tests should be failing based on the current implementation and represent unimplemented functionality?

**Comment by mgree** [comment]
Yeah, I think that's right.

**Comment by angelhof** [comment]
@mgree I fixed a few tests and skipped a few others that seemed like they should not pass with our current implementation. However I have a few questions that I am not sure about:
1. There are some tests failing based on the quotes. If I understand correctly, expansion is supposed to remove quotes in the shell, however, it doesn't seem to be correct to remove quotes when pretty-printing the script (since the behavior would be different, e.g., `grep "foo bar"` would turn into `grep foo bar`). Am I missing something? If I am understanding correctly, a solution could be to test expansion results on the AST data structure (instead of by pretty printing and comparing the shell scripts). To do that, we would have to define an expanded AST class based on the semantics of expansion.
2. I am not sure I understand the specification of `safe_command`. When is a command supposed to be safe to expand?

**Comment by mgree** [comment]
Well, the field structure should tell us how to pretty print, and the pretty printer should quote whitespace within a string...

For 2, I think it's a bit of a relic and I'm not certain we should keep it, but `safe_command` was supposed to return `True` when given a command AST that could be run in advance without risk of side-effect.

**Comment by angelhof** [comment]
Great, so I think that all failing tests are due to the tests being wrong and not the implementation. I paste the failing tests and their expected output below. 

```sh
$ cat safe4.sh
echo ${PWD} is fine to show
```
```
In safe4.sh, expected:
        echo '/Users/mgree/pash/compiler' is fine to show
Got:
        echo /Users/mgree/pash/compiler is fine to show
```

Our expansion seems to be returning the correct value. I don't see why it should quote the variable. For reference:

```sh
$ a="1 2"
$ args() { echo $1 -- $2; }
$ args $a
1 -- 2
```

Similarly:

```sh
$ cat safe1.sh
echo ~ is always safe
```

```
In safe1.sh, expected:
        echo '/Users/mgree' is always safe
Got:
        echo /Users/mgree is always safe
```

Finally, safe2.sh has the inverse issue:

```sh
$ cat safe2.sh
echo "quoting safe stuff is safe"
```

```
In safe2.sh, expected:
        echo quoting safe stuff is safe
Got:
        echo "quoting safe stuff is safe"
```

Should we ever split and unquote in expansion? I wouldn't think so.

@mgree if you don't disagree with the above, I will fix the tests and merge the PR

**Comment by mgree** [comment]
You're definitely right on the first two. I don't think we would need to split and unquote in expansion---and in any case, it's only safe to do so after globbing, which we aren't doing yet.

In the speculative context, we should remember that globbing is a bit sensitive: it involves reading the filesystem!

**Comment by mgree** [comment]
Oh, shoot, meant to respond to that. Quotes indeed should only need to be removed if we're trying to do field splitting ourselves. If we stop short of that, we should be fine leaving them in (so long as our pretty printer is sufficiently careful).

**Pull request merged**
